# Generated by Django 2.2 on 2019-05-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=100)),
                ('brief', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DownUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('update_time', models.CharField(max_length=20)),
                ('down_url', models.CharField(max_length=100)),
            ],
        ),
    ]
